'use strict';
const {test}=require('node:test');
const assert=require('node:assert/strict');
const G=require('../game.js'),J=require('../journey.js'),P=require('../persistence.js');
const valid=s=>G.validate(s)&&J.validate(s);
const fresh=()=>G.fresh('demo','ミオ','fox',Date.UTC(2026,8,11,3),()=>.5);
function memory(){const data=new Map();return{data,getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,String(v)),removeItem:k=>data.delete(k)};}
test('the first save and read preserve the full village',()=>{const storage=memory(),store=P.create(storage,valid),s=fresh();const result=store.commit(s,null);assert(result.ok);assert.deepEqual(store.read('demo').state,s);assert.equal(store.read('demo').token,result.token);});
test('the last good save is kept before the next write',()=>{const storage=memory(),store=P.create(storage,valid),s=fresh();const a=store.commit(s);s.coins=42;const b=store.commit(s,a.token);assert(b.ok);assert.equal(JSON.parse(storage.getItem(P.key('demo')+'-backup')).coins,30);});
test('corrupted primary data is restored from a validated backup',()=>{const storage=memory(),store=P.create(storage,valid),s=fresh();const a=store.commit(s);s.coins=42;store.commit(s,a.token);storage.setItem(P.key('demo'),'{broken');const r=store.read('demo');assert(r.recovered);assert.equal(r.state.coins,30);assert(store.commit(r.state,r.token).ok);assert.equal(storage.getItem(P.key('demo')+'-unreadable'),'{broken');assert(valid(store.read('demo').state));});
test('unreadable data without a backup is not silently treated as a saved village',()=>{const storage=memory(),store=P.create(storage,valid);storage.setItem(P.key('demo'),'{}');const r=store.read('demo');assert(r.unreadable);assert.equal(r.state,null);});
test('a stale writer cannot replace a newer saved state',()=>{const storage=memory(),store=P.create(storage,valid),s=fresh();const first=store.commit(s);const old=structuredClone(s);s.coins=77;const latest=store.commit(s,first.token);old.coins=999;const rejected=store.commit(old,first.token);assert(!rejected.ok);assert.equal(rejected.reason,'conflict');assert.equal(rejected.state.coins,77);assert.equal(storage.getItem(P.key('demo')),latest.token);});
test('an invalid import never mutates storage',()=>{const storage=memory(),store=P.create(storage,valid),s=fresh();const a=store.commit(s);s.coins=-1;assert(!store.commit(s,a.token).ok);assert.equal(storage.getItem(P.key('demo')),a.token);});
test('backup quota failure keeps the existing primary intact',()=>{const storage=memory(),store=P.create(storage,valid),s=fresh();const first=store.commit(s);storage.setItem=(k,v)=>{if(k.endsWith('-backup'))throw new Error('QuotaExceeded');storage.data.set(k,v);};s.coins=50;assert(!store.commit(s,first.token).ok);assert.equal(storage.getItem(P.key('demo')),first.token);});
test('storage refusal is reported without throwing into the game',()=>{const storage={getItem(){throw new Error('Denied');},setItem(){throw new Error('Denied');},removeItem(){throw new Error('Denied');}},store=P.create(storage,valid);assert(store.read('demo').unavailable);assert.equal(store.commit(fresh()).reason,'storage-unavailable');assert(!store.clear('demo'));});
test('a failed last-mode preference does not invalidate a successful save',()=>{const storage=memory(),set=storage.setItem;storage.setItem=(k,v)=>{if(k==='forest-child-mvp-mode')throw new Error('Denied');set(k,v);};const store=P.create(storage,valid);assert(store.commit(fresh()).ok);assert(store.read('demo').state);});
test('demo and real saves stay isolated during reset',()=>{const storage=memory(),store=P.create(storage,valid),a=fresh(),b=fresh();b.mode='real';store.commit(a);store.commit(b);assert(store.clear('demo'));assert.equal(store.read('demo').state,null);assert.equal(store.read('real').state.mode,'real');});
test('a valid backup from a different mode is never recovered into the wrong village',()=>{const storage=memory(),store=P.create(storage,valid),s=fresh();s.mode='real';storage.setItem(P.key('demo')+'-backup',JSON.stringify(s));assert.equal(store.read('demo').state,null);});
test('a deleted primary cannot be recreated by a stale tab without confirmation',()=>{const storage=memory(),store=P.create(storage,valid),s=fresh();const first=store.commit(s);assert(store.clear('demo'));assert.equal(store.commit(s,first.token).reason,'conflict');assert.equal(store.read('demo').state,null);});
